apiVersion: apps/v1
kind: Deployment

metadata:
  name: retail-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: retail

  template:
    metadata:
      labels:
        app: retail

    spec:
      containers:
      - name: retail-app
        image: kratinverma02/retail-app:latest
        ports:
        - containerPort: 3000
